### ISSUE TITLE
更新后使用不了

### ISSUE THREAD

**Issue by lsCoding666** [jh-leong/wecom-chatgpt#10]
这个api接受没问题
![image](https://user-images.githubusercontent.com/73888354/232064526-cfdce1ab-67b8-4a4f-9904-9b9dd6f905b8.png)
ip白名单应该也没问题
日志空
![image](https://user-images.githubusercontent.com/73888354/232064774-d05a0135-b5bc-4e4b-a309-95ba8bd04f32.png)
但是发送了很多消息
![image](https://user-images.githubusercontent.com/73888354/232064864-2a33d9a8-0858-4fe0-bbcc-4ba14fdb5aaf.png)

**Comment by lsCoding666** [comment]
![image](https://user-images.githubusercontent.com/73888354/232065101-37a09511-b3af-4f52-b801-086acedc9443.png)

**Comment by lsCoding666** [comment]
代码确定一致 直接复制过去 然后把变量一个一个复制粘贴的。而且应该不会出错 出错了的话api接收消息设置那里就不能设置成功了

**Comment by jh-leong** [comment]
发送重复的内容有可能会忽略不回复，试试换个内容测试下，看看会有什么具体的日志？

**Comment by jh-leong** [comment]
麻烦老哥更新替换最新代码后，再测试看看

**Comment by jh-leong** [comment]
see #8
