### ISSUE TITLE
【企业微信主体域名校验无法通过】接收消息服务器配置失败

### ISSUE THREAD

**Issue by yin52133** [jh-leong/wecom-chatgpt#11]
我在这一步，4.4 WECOM_TOKEN & WECOM_ENCODING_AES_KEY 按要求配置完了么api。
但是laf发布后的地址填写到企业微信后，提示“域名主体校验未通过，需配置备案主体与当前企业主体相同或有关联关系的域名 ”
这个要怎么解决呢？

**Comment by yin52133** [comment]
![1 laf_fail](https://user-images.githubusercontent.com/17401848/236387060-a8c957e0-b19f-449b-b30b-c1045b6463c5.png)
![2 laf_fail](https://user-images.githubusercontent.com/17401848/236387065-6b091264-489f-403a-a77b-27bb07c0ea67.png)

**Comment by yin52133** [comment]
也已经按照https://github.com/jh-leong/wecom-chatgpt/issues/2，勾选了get

**Comment by jh-leong** [comment]
去社区搜了一波，发现是企微改了规则导致的（[相关规则](https://open.work.weixin.qq.com/wwopen/common/readDocument/40754#%E4%BB%80%E4%B9%88%E6%98%AF%E5%85%B3%E8%81%94%E4%B8%BB%E4%BD%93)），现在绑定的所有域名都需要校验企业主体域名，之前没有这个限制。

企业主体域名需要准备相关资料进行备案，而且还得找企业微信的在线客服审核啥的。

简而言之，以后个人可能没办法这样白嫖企业微信了。。。这个项目估计也要关了，有点可惜

**Comment by yin52133** [comment]
> 去社区搜了一波，发现是企微改了规则导致的（[相关规则](https://open.work.weixin.qq.com/wwopen/common/readDocument/40754#%E4%BB%80%E4%B9%88%E6%98%AF%E5%85%B3%E8%81%94%E4%B8%BB%E4%BD%93)），现在绑定的所有域名都需要校验企业主体域名，之前没有这个限制。
> 
> 企业主体域名需要准备相关资料进行备案，而且还得找企业微信的在线客服审核啥的。
> 
> 简而言之，以后个人可能没办法这样白嫖企业微信了。。。这个项目估计也要关了，有点可惜

那太可惜了
