### ISSUE TITLE
域名主体校验未通过，需配置备案主体与当前企业主体相同或有关联关系的域名

### ISSUE THREAD

**Issue by zhangsan6663** [jh-leong/wecom-chatgpt#12]
域名主体校验未通过，需配置备案主体与当前企业主体相同或有关联关系的域名。这个怎么办？

**Comment by jh-leong** [comment]
企微方面的限制， [参考这个 issues](https://github.com/jh-leong/wecom-chatgpt/issues/11#issuecomment-1535791921)

**Comment by zhangsan6663** [comment]
我看其他项目，能否通过Nginx转发请求？我倒是有企业备案域名，就是想试试这个项目

**Comment by jh-leong** [comment]
完全可以呀，企微相关的配置能过就行，具体服务端逻辑可以按需实现
