### ISSUE TITLE
“设置API接收 - 接受消息服务器配置” 无法保存

### ISSUE THREAD

**Issue by huze210** [jh-leong/wecom-chatgpt#2]
open openapi回调地址请求不通过，没办法保存呜呜呜，请教一下这是怎么回事？纯小白

**Comment by jh-leong** [comment]
> 

是指哪一步出问题啦，有没有具体页面截图瞧瞧？试试再跟着教程一步一步检查下，看看有没有错漏或者输入错误啥的

**Comment by lsCoding666** [comment]
<img width="941" alt="image" src="https://user-images.githubusercontent.com/73888354/229691566-fbdd2710-3674-469d-a5b7-9c280912799a.png">
<img width="672" alt="image" src="https://user-images.githubusercontent.com/73888354/229691632-7ae31580-87f5-4677-8a6f-ed3e473c0a52.png">
填的都没问题 但是不通过

**Comment by lsCoding666** [comment]
<img width="720" alt="image" src="https://user-images.githubusercontent.com/73888354/229692048-4c8f5d80-da9b-4db6-b5f0-25ed08cd1d72.png">
<img width="306" alt="image" src="https://user-images.githubusercontent.com/73888354/229692081-9dabc742-edbf-4b65-a976-6fb6c929ebdf.png">

**Comment by lsCoding666** [comment]
应该是可信域名的问题 域名地址得用自己的才行

**Comment by lsCoding666** [comment]
<img width="414" alt="image" src="https://user-images.githubusercontent.com/73888354/229694240-40bbee99-f92a-409d-b5a0-b6c9c0bed509.png">
<img width="611" alt="image" src="https://user-images.githubusercontent.com/73888354/229694340-c6976191-d863-4a39-9a4c-3f04935a2495.png">

**Comment by lsCoding666** [comment]
已解决 ，得把get勾选上
<img width="609" alt="image" src="https://user-images.githubusercontent.com/73888354/229698109-e3e80620-cee7-4533-9e0e-aca042acb7d8.png">

**Comment by jh-leong** [comment]
> 已解决 ，得把get勾选上 <img alt="image" width="609" src="https://user-images.githubusercontent.com/73888354/229698109-e3e80620-cee7-4533-9e0e-aca042acb7d8.png">

感谢指正！！文档的配图有错误，已修复更新

**Comment by jh-leong** [comment]
> open openapi回调地址请求不通过，没办法保存呜呜呜，请教一下这是怎么回事？纯小白

<img width="507" alt="image" src="https://user-images.githubusercontent.com/52022476/229700064-629a2c60-5381-40d9-998a-d72cf5615881.png">

可在上图位置编辑一下云函数，把`GET`也勾选上就能保存成功了

**Comment by jh-leong** [comment]
已解决

**Comment by huze210** [comment]
感谢你好兄弟！我成功了，是因为那个loaf还是叫啥我忘记了，没有勾选上get这个选项，真的非常感谢你！谢谢！遇到一个纯小白的教程真的非常暖心呜呜呜

发自我的iPad
