### ISSUE TITLE
【ip 白名单配置问题】配置完成后，企业微信发送消息无回复

### ISSUE THREAD

**Issue by lsCoding666** [jh-leong/wecom-chatgpt#3]
配置完成后发现用不了。发消息给他没反应，也不会回复(･ェ･。) 我迷路啦 ~ 之类的报错。怀疑是企业微信配置有问题，但是看不到日志
<img width="560" alt="image" src="https://user-images.githubusercontent.com/73888354/229702107-343e06cb-4eb5-4ede-b53a-3351bcea5193.png">
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/73888354/229702160-b29ade87-157e-4a8f-b423-53bb1c947d5a.png">

**Comment by lsCoding666** [comment]
![image](https://user-images.githubusercontent.com/73888354/229702301-d3ac3b64-01d2-49df-ac7f-df289121ca91.png)

**Comment by lsCoding666** [comment]
<img width="703" alt="image" src="https://user-images.githubusercontent.com/73888354/229702485-8f97ddcd-8e60-4899-b836-eb734b8075cd.png">

**Comment by jh-leong** [comment]
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/52022476/229703383-0220966a-2f93-449c-8441-9473edf4c9aa.png">

老哥登录下 laf 的后台查看下日志，会有相关的 log，有可能是 ip 白名单没配置服务器 ip 导致（laf 的公网出口没有固定。。文档提供的 ip 白名单可能有遗漏）

**Comment by lsCoding666** [comment]
> <img alt="image" width="1255" src="https://user-images.githubusercontent.com/52022476/229703383-0220966a-2f93-449c-8441-9473edf4c9aa.png">
> 
> 老哥登录下 laf 的后台查看下日志，会有相关的 log，有可能是 ip 白名单没配置服务器 ip 导致（laf 的公网出口没有固定。。文档提供的 ip 白名单可能有遗漏）

确实是这样 遗漏的ip是 8.222.204.210
