### ISSUE TITLE
支持聊天上下文

### ISSUE THREAD

**Issue by kcxg** [jh-leong/wecom-chatgpt#4]

**Comment by jh-leong** [comment]
(･ェ･。) 已支持，请替换最新代码后，查看文档接入：[聊天上下文支持](https://github.com/jh-leong/wecom-chatgpt#5-%E8%81%8A%E5%A4%A9%E4%B8%8A%E4%B8%8B%E6%96%87%E6%94%AF%E6%8C%81)
