### ISSUE TITLE
更新后无法使用

### ISSUE THREAD

**Issue by zero202q** [jh-leong/wecom-chatgpt#5]
更新代码后，无回复消息。是不是哪一步漏了？更新之能用的。

**Comment by jh-leong** [comment]
确认过代码一致，配置无误的话，试试参考下这个 [issue](https://github.com/jh-leong/wecom-chatgpt/issues/3)，去日志面板看看有没有具体的报错信息

**Comment by zero202q** [comment]
<img width="847" alt="image" src="https://user-images.githubusercontent.com/62984572/230267368-747fc4f1-15d7-40e9-95e4-5f9d2e6453fb.png">

**Comment by jh-leong** [comment]
> <img alt="image" width="847" src="https://user-images.githubusercontent.com/62984572/230267368-747fc4f1-15d7-40e9-95e4-5f9d2e6453fb.png">

看日志是获取 openai 回复的时候出问题了，但是正常来说这一步出问题了企微也是能收到回复的，前后有其他日志信息不

**Comment by zero202q** [comment]
<img width="1252" alt="image" src="https://user-images.githubusercontent.com/62984572/230268902-20ca3650-2b4f-4cf7-923a-e64756a82c97.png">

**Comment by zero202q** [comment]
如果把上下文关闭以后是正常使用的，但开启上下文就会报错，就是上面图片的问题

**Comment by jh-leong** [comment]
我这边没有复现你的问题，怀疑是 openai api 返回的问题导致的，我给代码更新了取值保护以及更多日志信息 [commit](https://github.com/jh-leong/wecom-chatgpt/commit/13737d8a95c2ecbc6ecb7d9cd79493aa28a2aabd) 
老哥有需要的话，可以更新后再看看日志有没有更多信息

**Comment by zero202q** [comment]
还是这样
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/62984572/230327253-ce076163-1196-4386-ba03-84e57860ba6b.png">
<img width="918" alt="image" src="https://user-images.githubusercontent.com/62984572/230327354-e1eb587e-4cae-40eb-a13b-ce147fc0e91f.png">

**Comment by zero202q** [comment]
我这把USE_CHAT_CONTEXT: 1,开启上下文关闭，就能正常接收到信息。打开就报那个错

**Comment by jh-leong** [comment]
> 还是这样 <img alt="image" width="1018" src="https://user-images.githubusercontent.com/62984572/230327253-ce076163-1196-4386-ba03-84e57860ba6b.png"> <img alt="image" width="918" src="https://user-images.githubusercontent.com/62984572/230327354-e1eb587e-4cae-40eb-a13b-ce147fc0e91f.png">

看截图代码好像没更新？在 laf 后台，将代码替换成最新的，然后发布一下，企微重新发送下消息，再看看日志

**Comment by jh-leong** [comment]
see #8
